device_id = "acce13ba-db00-4c58-bba4-cb36acb5f752"
access_token = "b7adb249-b362-4670-b083-25203dbb55e3"
cert_pem = ""
key_pem = ""
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:839c:5aff:3cfe:51c4:600c"
wg_private_key = "mKuWr2j0VleP+S349vd7Gs2TGrXdp+X0Ia6B2nNsFmw="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "GqG2"
